<a href="https://colab.research.google.com/github/Sylwiaes/machine-learning-bootcamp/blob/main/01_numpy/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

* @author: krakowiakpawel9@gmail.com  
* @site: e-smartdata.org

### NumPy
>Strona biblioteki: [https://numpy.org/](https://numpy.org/)  
>Dokumentacja: [https://numpy.org/doc/](https://numpy.org/doc/)  
>
>Podstawowa biblioteka do obliczeń numerycznych w języku Python.
>
>Aby zainstalować bibliotekę NumPy, użyj polecenia poniżej:
```
pip install numpy
```

### Spis treści:
1. [Podstawy](#a1)
2. [Typy danych](#a2)
3. [Tworzenie tablic](#a3)
4. [Podstawowe operacje na tablicach](#a4)
5. [Generowanie liczb pseudolosowych](#a5)
6. [Podstawowe funkcje](#a6)
7. [Indeksowanie, Wycinanie](#a7)
8. [Iteracja po tablicach](#a8)
9. [Zmiana rozmiaru tablic](#a9)
10. [Maski logiczne](#a10)


### <a name='a1'></a> Podstawy

In [1]:
import numpy as np
np.__version__

'1.19.5'

In [ ]:
print(dir(np)) #sprawdzenie atrybutów biblioteki

In [ ]:
help(np.array) 

1D Array

In [3]:
x = np.array([1, 3])
x

array([1, 3])

In [8]:
print(x)

[1 3]


In [9]:
type(x)

numpy.ndarray

In [11]:
x.ndim #wymniar tablicy

1

In [12]:
x.shape #kształt, w tym przypadku tupla

(2,)

In [4]:
x.size #liczba elementów w naszej tablicy

2

In [13]:
x.dtype

dtype('int64')

In [16]:
x = np.array([1.3, 2.3, 1.4])
print(x)

[1.3 2.3 1.4]


In [17]:
x.dtype

dtype('float64')

2D Array

In [19]:
x = np.array([[1, 2], [-3, 1]])
x

array([[ 1,  2],
       [-3,  1]])

In [20]:
x.ndim

2

In [21]:
x.shape

(2, 2)

In [23]:
x = np.array([[1, 2, 4], [4, 2, 1]])
print(x)

[[1 2 4]
 [4 2 1]]


In [24]:
x.shape

(2, 3)

3D Array

In [31]:
x = np.array(
    [[[4, 3, 1],
      [3, 1, 2]],
     
     [[4, 1, 3],
      [4, 2, 1]],
     
     [[3, 2, 1],
      [4, 3, 2]]]
)
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]],

       [[3, 2, 1],
        [4, 3, 2]]])

In [32]:
x.ndim

3

In [33]:
x.shape

(3, 2, 3)

### <a name='a2'></a> Typy danych

In [34]:
A = np.array([1, 2, 3])
A.dtype

dtype('int64')

In [35]:
A = np.array([1.0, 2.3, 3.3])
A.dtype

dtype('float64')

In [36]:
A = np.array([1, 2, 3], dtype='float') #ustawiamy typy danych na float
A.dtype

dtype('float64')

In [38]:
A = np.array([1, 2, 3], dtype='complex')
A.dtype

dtype('complex128')

In [39]:
A = np.array([1.0, 2.3, 3.3], dtype='int') #konwertowanie danych na liczby całkowite
A.dtype

dtype('int64')

In [40]:
A

array([1, 2, 3])

In [41]:
A = np.array([True, False])
A.dtype

dtype('bool')

In [42]:
A = np.array([24, 120, 230], dtype=np.int8) #przedstawiamy dane dla 8-bitowej tablicy; pomocne przy budowaniu obrazów
A.dtype

dtype('int8')

In [43]:
A = np.array([24, 120, 230], dtype=np.uint8) #od 0 do 255 bitów
A.dtype

dtype('uint8')

### <a name='a3'></a> Tworzenie tablic

In [44]:
np.zeros(shape=(4, 10)) #funkcja wbudowana

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [45]:
np.zeros(shape=(4, 10), dtype='int') #liczby całkowite; funkcja uzywana do tworzenia masek do zdjęć

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [46]:
np.ones(shape=(5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [47]:
np.ones(shape=(5, 5), dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [49]:
np.full(shape=(3, 3), fill_value=4, dtype='int') #tablica z wymiarem 3x3 z wypełnioną wartością 4

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [6]:
np.arange(10) #funkcja arange do tworzenia tablicy array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
np.arange(start=5, stop=10)

array([5, 6, 7, 8, 9])

In [57]:
np.arange(start=10, stop=100, step=10) #step roznąco

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [58]:
np.arange(start=100, stop=10, step=-10) #step malejaco

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [59]:
np.arange(start=0, stop=1, step=0.05) #step na float

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [62]:
np.linspace(start=0, stop=1, num=10) #funkcja linspace podobna do funkcji arange; num-mówi o liczbie, ile równorozłożonych elementów chcemy wygenerować z przedziału

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [64]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [65]:
A.reshape((3, 5)) #zmiana rozłożenia elementów

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [66]:
A.reshape((3, -1)) #w przypadku, gdy nie chcemy liczyć ma być kolumn, to wpisujemy liczbę wierszy, którą chcemy dostać i liczbę -1 jako kolumny. Python sam dostosuje kolumny

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [67]:
A.reshape((-1, 3)) #wiersz dobrany automatycznie

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

### <a name='a4'></a> Podstawowe operacje na tablicach

In [8]:
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [69]:
A + B

array([6, 0, 7, 4])

In [70]:
A - B

array([0, 2, 1, 0])

In [71]:
A * B

array([ 9, -1, 12,  4])

In [72]:
A / B #należy pamiętać, aby tablica przez którą dzielimy nie zawierała 0

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [9]:
np.add(A, B)

array([6, 0, 7, 4])

In [77]:
np.subtract(A, B)

array([0, 2, 1, 0])

In [78]:
np.multiply(A, B)

array([ 9, -1, 12,  4])

In [79]:
np.divide(A, B)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [73]:
A + 3

array([6, 4, 7, 5])

In [74]:
2 * A

array([6, 2, 8, 4])

In [75]:
A + 3*B

array([12, -2, 13,  8])

Mnożenie macierzowe

In [84]:
X = np.array([[1, 3], [-2, 0]])
Y = np.array([[6, 0], [-1, 2]])
print(X, '\n')
print(Y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


In [81]:
X * Y #pomnożymy element po elemencie z każdej macierzy, co nie jest typowym mnożeniem jak w algebrze

array([[6, 0],
       [2, 0]])

In [85]:
np.dot(X, Y) #mnożenie macierzowe

array([[  3,   6],
       [-12,   0]])

In [86]:
X.dot(Y) #inaczej X*Y macierzowo

array([[  3,   6],
       [-12,   0]])

In [87]:
X @ Y #inny sposób przedstawienia mnożenia macierzowego X*Y

array([[  3,   6],
       [-12,   0]])

### <a name='a4'></a> Generowanie liczb pseudolosowych

In [15]:
np.random.seed(0) #ustalamy ziarno losowe

In [16]:
np.random.randn()

1.764052345967664

In [17]:
np.random.randn(10) #dostajemy tablice 10 losowo wygenerowanych elementów

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [18]:
np.random.randn(10, 4) #liczba wierszy jako liczba próbek

array([[ 1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877,  0.15494743],
       [ 0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682],
       [-0.30230275, -1.04855297, -1.42001794, -1.70627019],
       [ 1.9507754 , -0.50965218, -0.4380743 , -1.25279536],
       [ 0.77749036, -1.61389785, -0.21274028, -0.89546656]])

In [19]:
np.random.rand() #funkcja rand zwraca losową liczbę z przedziału 0-1

0.1965823616800535

In [20]:
np.random.rand(10)

array([0.36872517, 0.82099323, 0.09710128, 0.83794491, 0.09609841,
       0.97645947, 0.4686512 , 0.97676109, 0.60484552, 0.73926358])

In [21]:
np.random.rand(10, 2)

array([[0.03918779, 0.28280696],
       [0.12019656, 0.2961402 ],
       [0.11872772, 0.31798318],
       [0.41426299, 0.0641475 ],
       [0.69247212, 0.56660145],
       [0.26538949, 0.52324805],
       [0.09394051, 0.5759465 ],
       [0.9292962 , 0.31856895],
       [0.66741038, 0.13179786],
       [0.7163272 , 0.28940609]])

In [22]:
np.random.randint(10) #funkcja randint zwraca losowo liczbę całkowitą nieujemną<10

3

In [25]:
np.random.randint(low=10, high=101, size=10) #gdy chcemy wygenerować losową liczbę dwucyfrową; parametr size pozwala na ustalenie rozmiaru generowanych danych

array([82, 29, 82, 36, 76, 62, 77, 71, 24, 14])

In [107]:
np.random.choice([4, 2, 1, 3, 5]) #zwraca losowy element z przekazanej listy

4

In [108]:
np.random.choice(['python', 'java', 'sql'])

'sql'

In [27]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
np.random.shuffle(data) #tasuje nasze dane i zmienia postać naszych danych
data 

array([5, 4, 6, 1, 0, 3, 2, 9, 8, 7])

### <a name='a6'></a> Podstawowe funkcje

In [31]:
np.exp(1) #stałe liczba Eulera

2.718281828459045

In [112]:
np.sqrt(9) #pierwiastek kwadratowy w typie float

3.0

In [116]:
np.all([2, 3, 1]) #funkcja all zwraca wartość logiczną

True

In [35]:
np.any([0, 0, 0]) #funkcja, która sprawdza, czy jakikolwiek element jest prawdą

False

In [36]:
bool(1.3)

True

In [122]:
A = np.random.rand(5) #generujemy 5 wartości z rozkładu jednostajnego
A

array([0.97359871, 0.20728277, 1.09964197, 0.93989698, 0.606389  ])

In [126]:
np.argmax(A) #funkcja, która wyciąga indeks z największą wartością

2

In [127]:
A[np.argmax(A)] #wycinanie wartości

1.0996419726694937

In [128]:
np.argmin(A)

1

In [129]:
np.argsort(A) #sortuje elementy podając odpowiednio indeks; sortowanie domyślne rosnąco

array([1, 4, 3, 0, 2])

In [130]:
np.max(A) #wartość największa w tablicy

1.0996419726694937

In [131]:
np.min(A)

0.20728277243476398

In [132]:
np.mean(A)

0.765361887785039

In [133]:
np.median(A)

0.9398969807980037

In [134]:
np.std(A)

0.3232005342584192

###  <a name='a7'></a> Indeksowanie, Wycinanie

In [136]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
# A[idx], A[start:stop], A[:stop], A[start:]

In [137]:
A[2]

2

In [138]:
A[2:] #wycinanie indeksu od 2 do końca

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [139]:
A[:2]

array([0, 1])

In [ ]:
A[[0, 2]] #wycinanie indeksu 0 i 2

In [140]:
A[-1]

19

In [141]:
A[10:15]

array([10, 11, 12, 13, 14])

In [143]:
A = A.reshape(4, 5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [144]:
A[0] #wycięcie 1 wiersza

array([0, 1, 2, 3, 4])

In [145]:
A[1]

array([5, 6, 7, 8, 9])

In [146]:
A[:, 0] #wycięcie całej 1 kolumny

array([ 0,  5, 10, 15])

In [147]:
A[:, -1] #wycięcie ostatniej kolumny

array([ 4,  9, 14, 19])

In [148]:
A[1, 1] #wiersz 1 i kolumna 1

6

In [150]:
A[1:3, 1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [151]:
A[1, 2] = 14 #przypisanie liczby
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

### <a name='a8'></a> Iteracja po tablicach

In [152]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [153]:
for row in A:
  print(row) #iterowanie po każdym wierszu

[0 1 2 3 4]
[ 5  6 14  8  9]
[10 11 12 13 14]
[15 16 17 18 19]


In [154]:
for row in A:
  print(row[0]) #tylko indeks 0

0
5
10
15


In [155]:
for item in A.flat: #iterowanie po każdym elemencie tablicy
  print(item)

0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19


### <a name='a9'></a> Zmiana rozmiaru tablic

In [156]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [157]:
A.shape

(4, 5)

In [158]:
A.reshape(5, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 14],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [159]:
A.ravel() #pozwala wypłaszczyć nasze dane, czyli powrócić do postaci jednowymiarowej

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [160]:
A.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

### <a name='a10'></a> Maski logiczne

In [163]:
A = np.arange(start=-10, stop=10, step=0.5)
A.reshape(10, -1)

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [172]:
A > 0 #sprawdzamy, gdzie są wartości dodatnie; zwraca prawdę, gdy wartości są większe od 0, a fałsz, gdy te wartości są mniejsze

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True])

In [170]:
np.bitwise_and(A > -5, A < 5) #zwraca wartości True, gdzie oba warunki są spełnione

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False, False, False, False, False, False,
       False, False, False, False])

In [171]:
A[np.bitwise_and(A > -5, A < 5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [173]:
np.bitwise_or(A < -5, A > 5) #wartości logiczne, gdy spełniają jeden z dwóch podanych warunków

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True])