<a href="https://colab.research.google.com/github/Sylwiaes/machine-learning-bootcamp/blob/main/07_uczenie_glebokie/02_keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

* @author: krakowiakpawel9@gmail.com  
* @site: e-smartdata.org

### Tensorflow
>Strona biblioteki: [https://www.tensorflow.org/](https://www.tensorflow.org/)  
>Dokumentacja: [https://www.tensorflow.org/api_docs](https://www.tensorflow.org/api_docs)  
>
>Szybko rozwijająca się biblioteka do uczenia maszynowego i uczenia głębokiego rozwijana przez Google.
>
>Aby zainstalować bibliotekę tensorflow, użyj polecenia poniżej:
```
pip install tensorflow
```

### Keras
>Strona biblioteki: [https://keras.io/](https://keras.io/)  
>
>Wysokopoziomowy interfejs do budowy sieci neuronowych. Działa zarówno na Tensorflow, Theano oraz CNTK.
>
>Aby zainstalować bibliotekę keras, użyj polecenia poniżej:
```
pip install keras
```

### Model sekwencjny (Sequential Model):
1. [Wprowadzenie - pierwszy model](#a0)
2. [Funkcje aktywacji](#a1)
3. [Kompilacja modelu](#a2)
4. [Trenowanie modelu](#a3)
5. [Przykład - klasyfikacja binarna](#a4)
6. [Przykład - klasyfikacja wieloklasowa](#a5)
7. [Przykład - regresja](#a6)



Załadowanie biblioteki tensorflow


In [ ]:
%tensorflow_version 2.x
import tensorflow as tf
import numpy as np
import pandas as pd
import plotly.express as px
tf.__version__

'2.5.0'

### <a name='a0'></a>Wprowadzenie - pierwszy model
Model sekwencyjny to nic innego jak liniowy stos warstw.

In [ ]:
# utworzenie instancji klasy Sequential; klasa polega na budowaniu kolejnych warstw
from tensorflow.keras.models import Sequential

model = Sequential()
print(model)

Podstawowym elementem składowym modelu są warstwy. Aby dodać najbardziej standardową warstwę - warstwę gęsto połączoną należy użyć warstwy **Dense**. Aby dodać warstwę do modelu należy użyć metody *.add()*

In [ ]:
from tensorflow.keras.layers import Dense

model.add(Dense(units=4, input_shape=(10,))) #w 1 warstwie dodajemy parametr input_shape z wartością zmiennych opisujących naszą zmienną docelową 

Wyświetlenie podsumowania modelu: metoda *.summary()*

In [ ]:
model.summary() #wyswietlamy informacje o modelu

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 4)                 44        
Total params: 44
Trainable params: 44
Non-trainable params: 0
_________________________________________________________________


Dodanie kolejnej warstwy

In [ ]:
model.add(Dense(units=2))

model.summary()
#obliczenie Param-bierzemy kształt wyjściowej 1 warstwy=4, dodajemy 1 i mnożymy przez kształt warstwy 2

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 4)                 44        
_________________________________________________________________
dense_1 (Dense)              (None, 2)                 10        
Total params: 54
Trainable params: 54
Non-trainable params: 0
_________________________________________________________________


### <a name='a1'></a>Funkcje aktywacji
Istotnym elemenem sieci neuronowych jest dobór odpowiednich funkcji aktywacji. Funkcje aktywacji jak sama nazwa wskazuje są odpowiedzialne za aktywowanie odpowiednich neuronów podczas procesu uczenia.

Jeżeli nie określimy podczas dodawania warstwy funkcji aktywacji, domyślnie stosowana jest liniowa funkcja aktywacji, tzn. $a(x)=x$

Warstwa z liniową funkcją aktywacji może uczyć się tylko liniowych przekształceń danych wejściowych. Dlatego stosuje się różne funkcje aktywacji aby rozwiazywać problemy nieliniowe.

[Keras: Funkcje aktywacji](https://keras.io/activations/)

In [ ]:
from tensorflow.keras.activations import linear #jesli nie stosujemy żadnej warstwy, to będzie stosowana domyślnie funkcja liniowa

random_data = np.linspace(start=-3, stop=3, num=300)
data = pd.DataFrame({'data': random_data, 'linear': linear(random_data)})
data.head()

data    linear
0 -3.000000 -3.000000
1 -2.979933 -2.979933
2 -2.959866 -2.959866
3 -2.939799 -2.939799
4 -2.919732 -2.919732

In [ ]:
px.line(data, x='data', y='linear', width=500, height=400, range_y=[-3, 3])

In [ ]:
from tensorflow.keras.activations import sigmoid

data = pd.DataFrame({'data': random_data, 'sigmoid': sigmoid(random_data)})
data.head()

data   sigmoid
0 -3.000000  0.047426
1 -2.979933  0.048341
2 -2.959866  0.049272
3 -2.939799  0.050221
4 -2.919732  0.051187

In [ ]:
px.line(data, x='data', y='sigmoid', width=500, height=400, range_y=[-0.5, 1.5])

In [ ]:
from tensorflow.keras.activations import relu #funkcja relu zeruje wartości ujemne
#funkcja relu pozwala poprawić działanie sieci neuronowej i pozwala pracować z problemami nieliniowymi

data = pd.DataFrame({'data': random_data, 'relu': relu(random_data)})
data.head()

data  relu
0 -3.000000   0.0
1 -2.979933   0.0
2 -2.959866   0.0
3 -2.939799   0.0
4 -2.919732   0.0

In [ ]:
px.line(data, x='data', y='relu', width=500, height=400, range_y=[-0.5, 1.5])

In [ ]:
from tensorflow.keras.activations import tanh #funkcja tangensa hiperbolicznego, stosowana jako zamiennik do funkcji sigmoid lub relu, w przypadku, gdy nie radzą sobie z problemem

data = pd.DataFrame({'data': random_data, 'tanh': tanh(random_data)})
data.head()

data      tanh
0 -3.000000 -0.995055
1 -2.979933 -0.994853
2 -2.959866 -0.994643
3 -2.939799 -0.994424
4 -2.919732 -0.994196

In [ ]:
px.line(data, x='data', y='tanh', width=500, height=400, range_y=[-1.5, 1.5])

In [ ]:
model = Sequential()
model.add(Dense(units=8, activation='relu', input_shape=(10,)))
model.add(Dense(units=1, activation='sigmoid'))
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_2 (Dense)              (None, 8)                 88        
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 9         
Total params: 97
Trainable params: 97
Non-trainable params: 0
_________________________________________________________________


### <a name='a2'></a>Kompilacja modelu
Przed rozpoczęciem trenowania sieci należy odpowiednio skonfigurować proces uczenia. W tym kroku określamy:
* rodzaj optymalizatora ([Keras - Optymalizatory](https://keras.io/optimizers/)) - minimalizuje funkcję straty
* funkcję straty ([Keras - Funkcje Straty](https://keras.io/losses/))
* metryki, które będziemy obserwować podczas trenowania sieci ([Keras - Metryki](https://keras.io/metrics/)) - najczęście stosowana metryka to accuracy

In [ ]:
# klasyfikacja binarna
model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

# klasyfikacja wieloklasowa
model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# regresja
model.compile(optimizer='rmsprop',
              loss='mse')

### <a name='a3'></a>Trenowanie modelu
Za dane wejściowe do modelu należy przekazać Numpy arrays:
* **epochs** - krotność przejścia danych przez sieć w procesie uczenia
* **batch_size** - rozmiar wsadu po którym następuje aktualizacja wag, domyślna wartość=32
* **validation_split** - część danych treningowych, które zostaną wykorzystane jako zbiór walidacyjny; ustalony opcjonalnie, ale warto go dodać, bo widzimy jak nasz model działa na danych, których nie widział; domyślnie to wartość 0.2 oznacza, że będziemy mieć 20% danych przeznaczonych na zbiór walidacyjny
* **validation_data** - (x_val, y_val) - dane wykorzystane do walidacji modelu

In [ ]:
# model.fit(data, labels, epochs=10, batch_size=32)
# model.fit(data, labels, epochs=10, batch_size=32, validation_split=0.2)
# model.fit(data, labels, epochs=10, batch_size=32, validation_data=(x_val, y_val))

### <a name='a4'></a> Przykład - klasyfikacja binarna

In [ ]:
data = np.random.randn(10000, 150) #10000 próbek i 150 danych niezależnych
labels = np.random.randint(2, size=(10000, 1))

print(data.shape)
print(labels.shape)

(10000, 150)
(10000, 1)


In [ ]:
data[:3]

In [ ]:
labels[:10]

array([[0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0]])

In [ ]:
model = Sequential() #budujemy instancję modelu
model.add(Dense(units=32, activation='relu', input_shape=(150,))) #wrzucamy 1 warstwę z 32 neuronami
model.add(Dense(1, activation='sigmoid')) #w ostatniej warstwie mamy 1 neuron; funkcja sigmoid zwróci nam prawdopodobieństwa klas

model.compile(optimizer='rmsprop',    #kompilacja modelu
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20) #dane przejdą 20 razy przez sieć

Epoch 1/20
313/313 [==============================] - 1s 1ms/step - loss: 0.7596 - accuracy: 0.4973
Epoch 2/20
313/313 [==============================] - 0s 1ms/step - loss: 0.6958 - accuracy: 0.5429
Epoch 3/20
313/313 [==============================] - 0s 1ms/step - loss: 0.6756 - accuracy: 0.5769
Epoch 4/20
313/313 [==============================] - 0s 1ms/step - loss: 0.6599 - accuracy: 0.6050
Epoch 5/20
313/313 [==============================] - 0s 1ms/step - loss: 0.6456 - accuracy: 0.6282
Epoch 6/20
313/313 [==============================] - 0s 1ms/step - loss: 0.6312 - accuracy: 0.6501
Epoch 7/20
313/313 [==============================] - 0s 1ms/step - loss: 0.6166 - accuracy: 0.6668
Epoch 8/20
313/313 [==============================] - 0s 1ms/step - loss: 0.6017 - accuracy: 0.6780
Epoch 9/20
313/313 [==============================] - 0s 1ms/step - loss: 0.5876 - accuracy: 0.6936
Epoch 10/20
313/313 [==============================] - 0s 1ms/step - loss: 0.5726 - accuracy: 0.7078

In [ ]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20, batch_size=64) #dodajemy parametr batch_size, czyli liczba wsadów, czyli aktualizujemy wagi co 64 próbki, wcześniej był to domyślnie 32

Epoch 1/20
157/157 [==============================] - 1s 1ms/step - loss: 0.7598 - accuracy: 0.5086
Epoch 2/20
157/157 [==============================] - 0s 1ms/step - loss: 0.7008 - accuracy: 0.5403
Epoch 3/20
157/157 [==============================] - 0s 1ms/step - loss: 0.6813 - accuracy: 0.5659
Epoch 4/20
157/157 [==============================] - 0s 1ms/step - loss: 0.6682 - accuracy: 0.5881
Epoch 5/20
157/157 [==============================] - 0s 1ms/step - loss: 0.6561 - accuracy: 0.6059
Epoch 6/20
157/157 [==============================] - 0s 1ms/step - loss: 0.6455 - accuracy: 0.6246
Epoch 7/20
157/157 [==============================] - 0s 1ms/step - loss: 0.6346 - accuracy: 0.6455
Epoch 8/20
157/157 [==============================] - 0s 1ms/step - loss: 0.6235 - accuracy: 0.6555
Epoch 9/20
157/157 [==============================] - 0s 1ms/step - loss: 0.6134 - accuracy: 0.6683
Epoch 10/20
157/157 [==============================] - 0s 1ms/step - loss: 0.6036 - accuracy: 0.6852

In [ ]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20, batch_size=32, validation_split=0.2) #dodajemy parametr validation_split
#z poniższego wygenerowania widać, że accuracy na zbiorze treningowym się poprawia, ale na zbiorze walidacyjnym pogarsza

Epoch 1/20
250/250 [==============================] - 1s 2ms/step - loss: 0.7519 - accuracy: 0.5064 - val_loss: 0.7249 - val_accuracy: 0.5045
Epoch 2/20
250/250 [==============================] - 0s 2ms/step - loss: 0.6937 - accuracy: 0.5534 - val_loss: 0.7227 - val_accuracy: 0.4875
Epoch 3/20
250/250 [==============================] - 0s 2ms/step - loss: 0.6740 - accuracy: 0.5806 - val_loss: 0.7246 - val_accuracy: 0.4920
Epoch 4/20
250/250 [==============================] - 0s 2ms/step - loss: 0.6579 - accuracy: 0.6086 - val_loss: 0.7294 - val_accuracy: 0.5025
Epoch 5/20
250/250 [==============================] - 0s 2ms/step - loss: 0.6432 - accuracy: 0.6355 - val_loss: 0.7342 - val_accuracy: 0.4975
Epoch 6/20
250/250 [==============================] - 0s 2ms/step - loss: 0.6281 - accuracy: 0.6549 - val_loss: 0.7433 - val_accuracy: 0.4945
Epoch 7/20
250/250 [==============================] - 0s 2ms/step - loss: 0.6131 - accuracy: 0.6750 - val_loss: 0.7507 - val_accuracy: 0.4865
Epoch 

In [ ]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

history = model.fit(data, labels, epochs=20, batch_size=32, validation_split=0.2, verbose=0) #dodanie parametru verbose-pozwala na wyświetlenie finalnego tekstu
history 

In [ ]:
metrics = history.history
metrics.keys()

dict_keys(['loss', 'accuracy', 'val_loss', 'val_accuracy'])

In [ ]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

history = model.fit(data, labels, epochs=20, batch_size=32, validation_split=0.2, verbose=1) #użycie parametru verbose=1

Epoch 1/20
250/250 [==============================] - 1s 2ms/step - loss: 0.7385 - accuracy: 0.5036 - val_loss: 0.7269 - val_accuracy: 0.4925
Epoch 2/20
250/250 [==============================] - 0s 2ms/step - loss: 0.6939 - accuracy: 0.5501 - val_loss: 0.7227 - val_accuracy: 0.4865
Epoch 3/20
250/250 [==============================] - 0s 2ms/step - loss: 0.6766 - accuracy: 0.5781 - val_loss: 0.7239 - val_accuracy: 0.4895
Epoch 4/20
250/250 [==============================] - 0s 2ms/step - loss: 0.6624 - accuracy: 0.5991 - val_loss: 0.7281 - val_accuracy: 0.4875
Epoch 5/20
250/250 [==============================] - 0s 2ms/step - loss: 0.6492 - accuracy: 0.6216 - val_loss: 0.7311 - val_accuracy: 0.4860
Epoch 6/20
250/250 [==============================] - 0s 2ms/step - loss: 0.6356 - accuracy: 0.6440 - val_loss: 0.7391 - val_accuracy: 0.4820
Epoch 7/20
250/250 [==============================] - 0s 2ms/step - loss: 0.6209 - accuracy: 0.6647 - val_loss: 0.7470 - val_accuracy: 0.4830
Epoch 

In [ ]:
test_data = np.random.randn(5, 150)
test_labels = np.random.randint(2, size=(5, 1))

In [ ]:
model.predict(test_data) #funkcja predict pokazuje nam prawdopodobieństwo danej klasy i w zależności, czy prawdopod. jest bliżej 1, czy 0, to przypisujemy tę klasę

array([[0.78603625],
       [0.38159966],
       [0.8606045 ],
       [0.24683797],
       [0.10432845]], dtype=float32)

In [ ]:
model.predict_proba(test_data) #identyczna funkcja do powyższej

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:430: UserWarning:

`model.predict_proba()` is deprecated and will be removed after 2021-01-01. Please use `model.predict()` instead.



array([[0.78603625],
       [0.38159966],
       [0.8606045 ],
       [0.24683797],
       [0.10432845]], dtype=float32)

In [ ]:
model.predict_classes(test_data) #zwraca konkretne klasy

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:455: UserWarning:

`model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).



array([[1],
       [0],
       [1],
       [0],
       [0]], dtype=int32)

### <a name='a5'></a> Przykład - klasyfikacja wieloklasowa

In [ ]:
data = np.random.random((10000, 150))
labels = np.random.randint(10, size=(10000, 1))

In [ ]:
print(data.shape)
print(labels.shape)

(10000, 150)
(10000, 1)


In [ ]:
labels[:10]

array([[7],
       [9],
       [5],
       [8],
       [0],
       [7],
       [7],
       [0],
       [8],
       [1]])

In [ ]:
from tensorflow.keras.utils import to_categorical #funkcja, która konwertuje klasy do tablicy numpy; wartość 1 będzie pojawiać się na miejscu w zależności od powyższej klasy labels
labels = to_categorical(labels, num_classes=10)
labels

array([[0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.]], dtype=float32)

In [ ]:
labels[1]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 1.], dtype=float32)

In [ ]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=10, activation='softmax')) #dodajemy tyle neuronów, ile mamy klas

model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, batch_size=32, epochs=30, validation_split=0.2)

Epoch 1/30
250/250 [==============================] - 1s 2ms/step - loss: 2.3178 - accuracy: 0.1021 - val_loss: 2.3028 - val_accuracy: 0.1115
Epoch 2/30
250/250 [==============================] - 0s 2ms/step - loss: 2.3038 - accuracy: 0.1131 - val_loss: 2.3025 - val_accuracy: 0.1085
Epoch 3/30
250/250 [==============================] - 0s 2ms/step - loss: 2.3014 - accuracy: 0.1139 - val_loss: 2.3050 - val_accuracy: 0.1070
Epoch 4/30
250/250 [==============================] - 0s 2ms/step - loss: 2.2999 - accuracy: 0.1154 - val_loss: 2.3074 - val_accuracy: 0.1020
Epoch 5/30
250/250 [==============================] - 0s 2ms/step - loss: 2.2980 - accuracy: 0.1160 - val_loss: 2.3072 - val_accuracy: 0.1085
Epoch 6/30
250/250 [==============================] - 0s 2ms/step - loss: 2.2964 - accuracy: 0.1192 - val_loss: 2.3124 - val_accuracy: 0.1145
Epoch 7/30
250/250 [==============================] - 0s 2ms/step - loss: 2.2947 - accuracy: 0.1186 - val_loss: 2.3110 - val_accuracy: 0.1190
Epoch 

In [ ]:
test_data = np.random.random((10, 150))

model.predict(test_data) #tam, gdzie prawdopodobieństwo będzie maksymalne, tam będzie nasza etykieta

array([[0.06440148, 0.05232339, 0.12625988, 0.12429369, 0.08980099,
        0.10967834, 0.13849577, 0.11009382, 0.09001628, 0.09463636],
       [0.11406983, 0.10864137, 0.10551243, 0.11036746, 0.09602603,
        0.06573106, 0.11372243, 0.09847464, 0.1092097 , 0.07824507],
       [0.16929969, 0.1948275 , 0.10558943, 0.11020967, 0.04946987,
        0.0525309 , 0.08560979, 0.08562473, 0.07357266, 0.07326572],
       [0.12289037, 0.07078976, 0.11899021, 0.05263653, 0.08295916,
        0.15647534, 0.08808529, 0.06708514, 0.1357374 , 0.10435077],
       [0.1535669 , 0.1412117 , 0.09607241, 0.07167321, 0.09187589,
        0.1234692 , 0.08570006, 0.14989997, 0.03326533, 0.05326533],
       [0.1046429 , 0.08695292, 0.13640529, 0.11639301, 0.06385175,
        0.09680387, 0.10870943, 0.11176197, 0.07263844, 0.10184035],
       [0.05852167, 0.10281017, 0.10081221, 0.14451665, 0.10252757,
        0.04582871, 0.19748726, 0.08656445, 0.13065286, 0.0302784 ],
       [0.07701448, 0.10776655, 0.0664231

In [ ]:
model.predict_classes(test_data) 

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/engine/sequential.py:455: UserWarning:

`model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).



array([6, 0, 1, 5, 0, 2, 6, 8, 6, 0])

### <a name='a6'></a> Przykład - regresja

In [ ]:
data = np.random.random((10000, 150))
labels = 50 * np.random.random(10000)

In [ ]:
labels[:10]

array([18.70666695, 19.88601801, 45.7715002 , 44.70766776, 14.43237131,
        8.97566539,  5.59726128, 34.41694501, 40.45244519, 26.87133692])

In [ ]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=1))

model.compile(optimizer='rmsprop',
              loss='mse') #funkcja straty średniogo błędu kwadratowego

model.fit(data, labels, epochs=30, batch_size=32, validation_split=0.2)

Epoch 1/30
250/250 [==============================] - 1s 2ms/step - loss: 263.7690 - val_loss: 208.7705
Epoch 2/30
250/250 [==============================] - 0s 2ms/step - loss: 213.9843 - val_loss: 208.1279
Epoch 3/30
250/250 [==============================] - 0s 1ms/step - loss: 213.1751 - val_loss: 208.8020
Epoch 4/30
250/250 [==============================] - 0s 1ms/step - loss: 213.2284 - val_loss: 208.1775
Epoch 5/30
250/250 [==============================] - 0s 1ms/step - loss: 212.6748 - val_loss: 208.2425
Epoch 6/30
250/250 [==============================] - 0s 2ms/step - loss: 212.4041 - val_loss: 208.3155
Epoch 7/30
250/250 [==============================] - 0s 1ms/step - loss: 212.1641 - val_loss: 208.5758
Epoch 8/30
250/250 [==============================] - 0s 1ms/step - loss: 211.9721 - val_loss: 208.8905
Epoch 9/30
250/250 [==============================] - 0s 1ms/step - loss: 211.9179 - val_loss: 208.5942
Epoch 10/30
250/250 [==============================] - 0s 1ms/st

In [ ]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=1))

model.compile(optimizer='rmsprop',
              loss='mae',
              metrics=['mse'])

model.fit(data, labels, epochs=10, batch_size=32, validation_split=0.2)

Epoch 1/10
250/250 [==============================] - 1s 2ms/step - loss: 13.9038 - mse: 276.5324 - val_loss: 12.5858 - val_mse: 209.3413
Epoch 2/10
250/250 [==============================] - 0s 2ms/step - loss: 12.6751 - mse: 213.9536 - val_loss: 12.5834 - val_mse: 208.7541
Epoch 3/10
250/250 [==============================] - 0s 2ms/step - loss: 12.6542 - mse: 213.6176 - val_loss: 12.6372 - val_mse: 213.1251
Epoch 4/10
250/250 [==============================] - 0s 1ms/step - loss: 12.6605 - mse: 213.6947 - val_loss: 12.5974 - val_mse: 209.0888
Epoch 5/10
250/250 [==============================] - 0s 1ms/step - loss: 12.6371 - mse: 213.2295 - val_loss: 12.5894 - val_mse: 209.7487
Epoch 6/10
250/250 [==============================] - 0s 2ms/step - loss: 12.6381 - mse: 212.8197 - val_loss: 12.5930 - val_mse: 209.3206
Epoch 7/10
250/250 [==============================] - 0s 1ms/step - loss: 12.6139 - mse: 212.8222 - val_loss: 12.6147 - val_mse: 209.7243
Epoch 8/10
250/250 [==============

In [ ]:
test_data = np.random.random((10, 150))

model.predict(test_data)

array([[25.710756],
       [24.376913],
       [22.324171],
       [24.472927],
       [21.625185],
       [25.945913],
       [27.040735],
       [22.436934],
       [24.231878],
       [25.026926]], dtype=float32)